const AGENTS=[
 {id:'outline',icon:'✦',name:'大纲构建',desc:'从灵感建立世界、人物、冲突与完整故事弧',target:'outline'},
 {id:'chapter',icon:'▤',name:'章节规划',desc:'拆解当前篇章目标、节拍、冲突与章尾钩子',target:'chat'},
 {id:'write',icon:'✎',name:'正文写作',desc:'结合全部设定续写当前章节正文',target:'editor'},
 {id:'polish',icon:'◈',name:'语言润色',desc:'优化表达、氛围、节奏与画面感',target:'editor'},
 {id:'memory',icon:'◫',name:'角色记忆',desc:'提取人物状态、关系变化与关键事实',target:'memory'},
 {id:'check',icon:'✓',name:'剧情检查',desc:'检查逻辑矛盾、设定冲突和遗漏伏笔',target:'chat'},
 {id:'review',icon:'◇',name:'质量审稿',desc:'从开篇、节奏、爽点与可读性给出评分',target:'chat'},
 {id:'revise',icon:'↺',name:'精修编修',desc:'依据审稿意见完成编辑级重写',target:'editor'}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>Math.random().toString(36).slice(2,9); let currentAgent='write', saveTimer, generationStopped=false;
const starter=idea=>({id:uid(),title:'未命名作品',idea:idea||'',outline:'',world:'',memory:'',characters:[],chapters:[{id:uid(),title:'第一章：故事的开端',content:''}],activeChapter:0,versions:[],updated:Date.now()});
let state=JSON.parse(localStorage.getItem('inkverse-state')||'null')||{projects:[starter('')],active:0,settings:{endpoint:'',key:'',model:'gpt-4.1-mini'}};
function project(){return state.projects[state.active]}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function persist(){project().updated=Date.now();localStorage.setItem('inkverse-state',JSON.stringify(state));$('#saveState').textContent='已保存'}
function schedule(){ $('#saveState').textContent='保存中…';clearTimeout(saveTimer);saveTimer=setTimeout(persist,450)}
function renderAgentUI(){
 $('#agentCards').innerHTML=AGENTS.map(a=>`<div class="agentcard"><div class="ico">${a.icon}</div><h3>${a.name} Agent</h3><p>${a.desc}</p></div>`).join('');
 $('#agentList').innerHTML=AGENTS.map(a=>`<button class="agent-chip ${a.id===currentAgent?'active':''}" data-agent="${a.id}" title="${a.desc}">${a.icon} ${a.name}</button>`).join('');
 $$('.agent-chip').forEach(b=>b.onclick=()=>{currentAgent=b.dataset.agent;renderAgentUI();$('#agentChat').innerHTML=`<div class="message ai"><b>${AGENTS.find(a=>a.id===currentAgent).name} Agent</b> 已就绪。<br>${AGENTS.find(a=>a.id===currentAgent).desc}。请补充要求，或直接点击发送。</div>`});
}
function render(){let p=project(),c=p.chapters[p.activeChapter];$('#projectSwitch').textContent=p.title+'⌄';$('#chapterTitle').value=c.title;$('#editor').value=c.content;$('#outlineText').value=p.outline;$('#worldText').value=p.world;$('#memoryText').value=p.memory;updateWords();$('#chapterList').innerHTML=p.chapters.map((x,i)=>`<div class="chapter ${i===p.activeChapter?'active':''}" data-i="${i}">${i+1}. ${escapeHtml(x.title)}</div>`).join('');$$('.chapter').forEach(x=>x.onclick=()=>{sync();p.activeChapter=+x.dataset.i;persist();render()});renderCharacters()}
function sync(){let p=project(),c=p.chapters[p.activeChapter];c.title=$('#chapterTitle').value;c.content=$('#editor').value;p.outline=$('#outlineText').value;p.world=$('#worldText').value;p.memory=$('#memoryText').value}
function updateWords(){let n=$('#editor').value.replace(/\s/g,'').length;$('#wordCount').textContent=n+' 字'}
function escapeHtml(s=''){return s.replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function enter(){let idea=$('#heroIdea').value.trim();if(idea&&!project().idea){project().idea=idea;project().title=idea.slice(0,12);persist()}$('#landing').classList.add('hidden');$('#app').classList.remove('hidden');render()}
function showView(name){$$('.view').forEach(v=>v.classList.add('hidden'));$('#'+name+'View').classList.remove('hidden');$$('#sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
function renderCharacters(){let p=project();$('#characterGrid').innerHTML=p.characters.length?p.characters.map((x,i)=>`<div class="character"><b>${escapeHtml(x.name)}</b><span>${escapeHtml(x.role)}</span><p>${escapeHtml(x.desc)}</p><button class="btn ghost small" data-delchar="${i}">删除</button></div>`).join(''):'<div class="chat-empty"><b>还没有角色</b><p>添加角色，或运行大纲构建 Agent 自动生成。</p></div>';$$('[data-delchar]').forEach(b=>b.onclick=()=>{p.characters.splice(+b.dataset.delchar,1);persist();renderCharacters()})}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').showModal()}
function contextFor(a,prompt){let p=project(),c=p.chapters[p.activeChapter];return `你是专业中文网文创作团队中的“${a.name} Agent”。任务：${a.desc}。\n作品名：${p.title}\n核心灵感：${p.idea}\n故事大纲：${p.outline}\n世界设定：${p.world}\n角色：${p.characters.map(x=>x.name+'('+x.role+')：'+x.desc).join(';')}\n长期记忆：${p.memory}\n当前章节：${c.title}\n当前正文：${c.content}\n用户补充要求：${prompt||'无'}\n请直接输出可用结果，不解释工作过程。`}
async function callAgent(isContinuation=false){let a=AGENTS.find(x=>x.id===currentAgent),prompt=isContinuation?'承接上文继续写作，不要重复已有内容，保持情节连贯。':$('#agentPrompt').value.trim();if(!isContinuation){generationStopped=false;$('#stopAgent').onclick=()=>{generationStopped=true;$('#stopAgent').classList.add('hidden');toast('将在本轮完成后停止')};$('#agentChat').innerHTML+=`<div class="message user">${escapeHtml(prompt||'请根据当前作品开始工作')}</div>`}$('#agentChat').innerHTML+=`<div class="message ai" id="thinking">${a.icon} ${a.name}${isContinuation?'正在续写':'正在思考'}…</div>`;$('#agentChat').scrollTop=$('#agentChat').scrollHeight;$('#runAgent').disabled=true;$('#stopAgent').classList.toggle('hidden',!(a.id==='write'&&$('#autoContinue').checked));let out='',failed=false;try{if(state.settings.endpoint&&state.settings.key){let url=state.settings.endpoint.replace(/\/$/,'')+(state.settings.endpoint.includes('/chat/completions')?'':'/chat/completions');let res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+state.settings.key},body:JSON.stringify({model:state.settings.model,messages:[{role:'user',content:contextFor(a,prompt)}],temperature:.8})});if(!res.ok)throw Error('接口返回 '+res.status);let data=await res.json();out=data.choices?.[0]?.message?.content||''}else out=demoOutput(a)}catch(e){failed=true;out='生成失败：'+e.message+'。请在设置中检查接口地址、密钥与跨域配置。'}$('#thinking')?.remove();let msg=document.createElement('div');msg.className='message ai';msg.innerHTML=`<b>${a.icon} ${a.name}</b>\n${escapeHtml(out)}<div class="actions"><button data-apply>${a.target==='editor'?'已自动写入':'应用结果'}</button><button data-copy>复制</button></div>`;$('#agentChat').append(msg);msg.querySelector('[data-apply]').onclick=()=>applyResult(a,out);msg.querySelector('[data-copy]').onclick=()=>navigator.clipboard.writeText(out).then(()=>toast('已复制'));if(!failed&&a.target==='editor')applyResult(a,out,true);$('#agentPrompt').value='';$('#agentChat').scrollTop=$('#agentChat').scrollHeight;let words=$('#editor').value.replace(/\s/g,'').length,target=Math.max(500,+$('#targetWords').value||3000);if(!failed&&!generationStopped&&a.id==='write'&&$('#autoContinue').checked&&words<target){setTimeout(()=>callAgent(true),500)}else{$('#runAgent').disabled=false;$('#stopAgent').classList.add('hidden');if(a.id==='write'&&words>=target)toast(`连续写作完成，共 ${words} 字`)}}
function demoOutput(a){let p=project(),c=p.chapters[p.activeChapter];let map={outline:`【故事核心】\n${p.idea||'一个普通人在旧世界崩塌前，发现自己是唯一能改写结局的人。'}\n\n【三幕主线】\n第一幕：异变发生，主角被迫离开熟悉的生活。\n第二幕：真相逐层揭开，盟友与敌人的界限开始模糊。\n第三幕：主角必须在个人执念与众人命运之间作出选择。\n\n【核心冲突】身份之谜、代价选择与不可逆的时间压力。`,chapter:`1. 用异常事件在前三百字制造悬念。\n2. 主角尝试用旧经验解释，却得到矛盾证据。\n3. 新角色携带关键线索登场。\n4. 一次失败让危机升级。\n5. 章尾钩子：主角发现线索指向自己。`,write:`${c.content?'\n\n':''}夜色沉得像一口没有回声的井。\n\n门外第三次响起敲击声时，他终于意识到，那并不是人在敲门。声音每隔七秒出现一次，精确得令人不安。\n\n他屏住呼吸，握住冰冷的门把。就在指尖触到金属的一瞬间，屋内所有钟表同时停了。\n\n停在他出生的那个时刻。`,polish:(c.content||'夜里有人敲门。他走过去，发现所有钟都停了。')+'\n\n窗外的风擦过玻璃，像谁在黑暗里磨着一把钝刀。',memory:`- ${c.title}：主角遭遇规律为七秒一次的神秘敲门声。\n- 屋内所有钟表停在主角出生时刻。\n- 主角尚不知道异象来源，警惕程度上升。`,check:'检查完成：\n✓ 人物动机基本成立\n✓ 场景时间连续\n△ “所有钟表同时停止”的触发机制尚未解释，建议后续两章内给出线索\n△ 当前章节缺少配角反应，可加入旁观证词增强可信度',review:'综合评分：82/100\n开篇吸引力 88｜节奏 84｜人物辨识度 73｜设定新鲜度 85\n\n优点：悬念进入快，意象统一。\n改进：主角的独特欲望还不够清晰；建议在危机中加入一个只有他会做出的选择。',revise:(c.content||'敲门声响了。他觉得有点奇怪。')+'\n\n第七秒，敲击如期而至。\n他没有去开门，而是先把桌上那只走快了十年的旧表扣进掌心——这是父亲留给他的唯一东西，也是屋里唯一还在走的钟。'};return map[a.id]}
function applyResult(a,out,silent=false){let p=project();if(a.target==='editor'){$('#editor').value=(a.id==='write'?$('#editor').value:'')+out;updateWords()}else if(a.target==='outline'){$('#outlineText').value=out;p.outline=out}else if(a.target==='memory'){$('#memoryText').value=(p.memory?p.memory+'\n':'')+out;p.memory=$('#memoryText').value}else{navigator.clipboard?.writeText(out)}sync();persist();if(!silent)toast(a.target==='chat'?'结果已复制':'已应用到作品')}
function newProject(){modal(`<h2>创建新作品</h2><div class="modal-fields"><label>作品名<input id="npTitle" placeholder="给故事一个名字"></label><label>一句话灵感<textarea id="npIdea" placeholder="主角是谁？他想要什么？什么阻止了他？"></textarea></label><label>类型<select id="npGenre"><option>玄幻奇幻</option><option>都市异能</option><option>悬疑推理</option><option>科幻末世</option><option>古代言情</option></select></label></div><div class="modal-actions"><button class="btn primary" type="button" id="createProject">创建作品</button></div>`);$('#createProject').onclick=()=>{let p=starter($('#npIdea').value);p.title=$('#npTitle').value||'未命名作品';state.projects.push(p);state.active=state.projects.length-1;persist();$('#modal').close();render();toast('作品已创建')}}
function settings(){modal(`<h2>模型设置</h2><p style="color:#777;font-size:13px">支持 OpenAI 兼容的 Chat Completions 接口。密钥仅保存在当前浏览器中。</p><div class="modal-fields"><label>接口地址<input id="setEndpoint" value="${escapeHtml(state.settings.endpoint)}" placeholder="https://api.example.com/v1"></label><label>API Key<input id="setKey" type="password" value="${escapeHtml(state.settings.key)}" placeholder="sk-..."></label><label>模型<input id="setModel" value="${escapeHtml(state.settings.model)}"></label></div><div class="modal-actions"><button class="btn primary" type="button" id="saveSettings">保存设置</button></div>`);$('#saveSettings').onclick=()=>{state.settings={endpoint:$('#setEndpoint').value,key:$('#setKey').value,model:$('#setModel').value};persist();$('#modal').close();toast('模型设置已保存')}}
function switchProject(){modal(`<h2>我的作品</h2><div class="modal-fields">${state.projects.map((p,i)=>`<button type="button" class="btn ${i===state.active?'dark':'ghost'}" data-project="${i}">${escapeHtml(p.title)} · ${p.chapters.length} 章</button>`).join('')}</div>`);$$('[data-project]').forEach(b=>b.onclick=()=>{sync();state.active=+b.dataset.project;persist();$('#modal').close();render()})}
function exportWork(){sync();let p=project(),text=`# ${p.title}\n\n> ${p.idea}\n\n## 故事大纲\n\n${p.outline}\n\n`+p.chapters.map(c=>`## ${c.title}\n\n${c.content}`).join('\n\n');let blob=new Blob([text],{type:'text/markdown;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=p.title+'.md';a.click();URL.revokeObjectURL(a.href);toast('作品已导出')}
$$('[data-enter]').forEach(b=>b.onclick=enter);$('#backHome').onclick=()=>{$('#app').classList.add('hidden');$('#landing').classList.remove('hidden')};$$('#sideNav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#editor').oninput=()=>{updateWords();schedule()};['chapterTitle','outlineText','worldText','memoryText'].forEach(id=>$('#'+id).oninput=schedule);$('#saveBtn').onclick=()=>{sync();persist();toast('已保存')};$('#addChapter').onclick=()=>{sync();project().chapters.push({id:uid(),title:`第${project().chapters.length+1}章：未命名`,content:''});project().activeChapter=project().chapters.length-1;persist();render()};$('#newProject').onclick=newProject;$('#settingsBtn').onclick=settings;$('#projectSwitch').onclick=switchProject;$('#exportBtn').onclick=exportWork;$('#runAgent').onclick=callAgent;$('#agentPrompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();callAgent()}};$('#addCharacter').onclick=()=>{modal(`<h2>添加角色</h2><div class="modal-fields"><label>姓名<input id="charName"></label><label>身份<input id="charRole" placeholder="主角 / 反派 / 导师"></label><label>人物设定<textarea id="charDesc" placeholder="目标、性格、秘密、人物弧……"></textarea></label></div><div class="modal-actions"><button type="button" class="btn primary" id="saveChar">保存角色</button></div>`);$('#saveChar').onclick=()=>{project().characters.push({name:$('#charName').value||'未命名',role:$('#charRole').value,desc:$('#charDesc').value});persist();renderCharacters();$('#modal').close()}};$('#historyBtn').onclick=()=>{sync();let p=project(),c=p.chapters[p.activeChapter];p.versions.unshift({time:new Date().toLocaleString(),title:c.title,content:c.content});p.versions=p.versions.slice(0,20);persist();modal(`<h2>版本记录</h2><p>已为当前章节创建快照。</p><div class="modal-fields">${p.versions.map((v,i)=>`<button type="button" class="btn ghost" data-version="${i}">${escapeHtml(v.title)} · ${v.time}</button>`).join('')}</div>`);$$('[data-version]').forEach(b=>b.onclick=()=>{let v=p.versions[+b.dataset.version];$('#chapterTitle').value=v.title;$('#editor').value=v.content;updateWords();$('#modal').close();toast('版本已恢复，请保存')})};renderAgentUI();render();
